CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    social_provider VARCHAR(50) NOT NULL,
    social_id VARCHAR(255),
    gender VARCHAR(10) NOT NULL,
    age INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE admin (
    admin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE owners (
    owner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE markets (
    market_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    thumbnail_url TEXT,
    location geography(Point,4326) NOT NULL,
    business_hours JSONB,
    market_phone_1 VARCHAR(255) NOT NULL,
    market_phone_2 VARCHAR(255),
    market_phone_primary SMALLINT NOT NULL,
    owner_phone VARCHAR(255) NOT NULL,
    owner_phone_2 VARCHAR(255),
    owner_phone_primary SMALLINT,
    brn VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE market_metadata (
    market_id BIGINT PRIMARY KEY,
    view_count INT NOT NULL
);

CREATE TABLE flyers (
    market_id BIGINT PRIMARY KEY,
    slug VARCHAR(255) NOT NULL,
    qr_code TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    deal_type VARCHAR(20) NOT NULL,
    thumbnail_url TEXT NOT NULL,
    original_price NUMERIC NOT NULL,
    discounted_price NUMERIC NOT NULL,
    category VARCHAR(50) NOT NULL,
    promotional_phrase VARCHAR(255),
    discount_start_date DATE NOT NULL,
    discount_end_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE product_metadata (
    product_id BIGINT PRIMARY KEY,
    view_count INT NOT NULL
);

CREATE TABLE default_product_thumbnails (
    dpt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    thumbnail_url TEXT NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_markets_owner_id ON markets (owner_id);
CREATE INDEX idx_products_market_id ON products (market_id);
