CREATE TABLE prepared_products (
    pp_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id BIGINT NOT NULL,
    name VARCHAR(255),
    thumbnail_url TEXT,
    original_price NUMERIC,
    discounted_price NUMERIC,
    category VARCHAR(50),
    promotional_phrase VARCHAR(255),
    discount_start_date DATE,
    discount_end_date DATE,
    draft_status VARCHAR(20) NOT NULL,
    fail_reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE INDEX idx_prepared_products_market_id ON prepared_products (market_id);
