springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

refresh-token:
  cookie:
    name: refresh_token
    path: /v1/auth/token/refresh
    same-site: Lax
    secure: ${REFRESH_COOKIE_SECURE:true}

server:
  forward-headers-strategy: framework
